// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protoapi.proto

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestNumbers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *RequestNumbers) Reset() {
	*x = RequestNumbers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNumbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNumbers) ProtoMessage() {}

func (x *RequestNumbers) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNumbers.ProtoReflect.Descriptor instead.
func (*RequestNumbers) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{0}
}

func (x *RequestNumbers) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RequestNumbers) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

type RequestStrLen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *RequestStrLen) Reset() {
	*x = RequestStrLen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStrLen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStrLen) ProtoMessage() {}

func (x *RequestStrLen) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStrLen.ProtoReflect.Descriptor instead.
func (*RequestStrLen) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{2}
}

func (x *RequestStrLen) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

var File_protoapi_proto protoreflect.FileDescriptor

var file_protoapi_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2c, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x22, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x22, 0x21, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x74, 0x72, 0x4c, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x32, 0x7b, 0x0a, 0x08, 0x50, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x44, 0x6f, 0x53, 0x75, 0x6d, 0x12, 0x0f,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x1a,
	0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x07, 0x44, 0x6f, 0x4d, 0x69,
	0x6e, 0x75, 0x73, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x0e, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x4c, 0x65, 0x6e, 0x1a, 0x07, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoapi_proto_rawDescOnce sync.Once
	file_protoapi_proto_rawDescData = file_protoapi_proto_rawDesc
)

func file_protoapi_proto_rawDescGZIP() []byte {
	file_protoapi_proto_rawDescOnce.Do(func() {
		file_protoapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoapi_proto_rawDescData)
	})
	return file_protoapi_proto_rawDescData
}

var file_protoapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protoapi_proto_goTypes = []interface{}{
	(*RequestNumbers)(nil), // 0: RequestNumbers
	(*Result)(nil),         // 1: Result
	(*RequestStrLen)(nil),  // 2: RequestStrLen
}
var file_protoapi_proto_depIdxs = []int32{
	0, // 0: Practice.DoSum:input_type -> RequestNumbers
	0, // 1: Practice.DoMinus:input_type -> RequestNumbers
	2, // 2: Practice.GetStrLength:input_type -> RequestStrLen
	1, // 3: Practice.DoSum:output_type -> Result
	1, // 4: Practice.DoMinus:output_type -> Result
	1, // 5: Practice.GetStrLength:output_type -> Result
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoapi_proto_init() }
func file_protoapi_proto_init() {
	if File_protoapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestNumbers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStrLen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoapi_proto_goTypes,
		DependencyIndexes: file_protoapi_proto_depIdxs,
		MessageInfos:      file_protoapi_proto_msgTypes,
	}.Build()
	File_protoapi_proto = out.File
	file_protoapi_proto_rawDesc = nil
	file_protoapi_proto_goTypes = nil
	file_protoapi_proto_depIdxs = nil
}
